trigger: none

parameters:
- name: environment
  displayName: Targeted a Dynamics/PowerPlatform Environment
  type: string
  default: development
  values:
  - development
  - test
  - uat
  - production

pool:
  vmImage: ubuntu-latest

jobs:
- job: Package_Import_Solution
  steps:
  - task: PowerPlatformToolInstaller@2
    displayName: 'Install Power Platform Tools'
    inputs:
      DefaultVersion: true
      AddToolsToPath: true
  - task: PowerPlatformPackSolution@2
    displayName: 'Package solution to unmanaged and managed packages'
    inputs:
      SolutionSourceFolder: '$(SolutionName)'
      SolutionOutputFile: '$(Build.ArtifactStagingDirectory)/$(SolutionName)/$(SolutionName).zip'
      SolutionType: 'Both'
  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: $(Build.ArtifactStagingDirectory)
      artifactName: power-platform-solutions
  - script: |
      find settings
      setting="settings/$(SolutionName)/${{ parameters.environment }}.json"
      echo "To check if file path: $setting exists"
      if [ -f $setting ]; then
        echo "Found setting JSON $setting"
        ls -l $setting
        echo "##vso[task.setvariable variable=settingJSON]$setting"
      else
        echo "No setting JSON found"
        echo "##vso[task.setvariable variable=settingJSON]false"
      fi
    displayName: 'Check if there is a setting file'
  - ${{ if eq(parameters.environment, 'development') }}:
    - task: PowerPlatformImportSolution@2
      condition: eq(variables['settingJSON'], 'false')
      displayName: Import unmanaged solution to ${{ parameters.environment }} instance
      inputs:
        authenticationType: 'PowerPlatformSPN'
        PowerPlatformSPN: 'PowerPlatform - Dev instance'
        SolutionInputFile: '$(Build.ArtifactStagingDirectory)/$(SolutionName)/$(SolutionName).zip'
        AsyncOperation: true
        MaxAsyncWaitTime: '60'
        ActivatePlugins: false
        PublishCustomizationChanges: true
    - task: PowerPlatformImportSolution@2
      condition: endsWith(variables['settingJSON'], '.json')
      displayName: Import unmanaged solution with settings to ${{ parameters.environment }} instance
      inputs:
        authenticationType: 'PowerPlatformSPN'
        PowerPlatformSPN: 'PowerPlatform - Dev instance'
        SolutionInputFile: '$(Build.ArtifactStagingDirectory)/$(SolutionName)/$(SolutionName).zip'
        UseDeploymentSettingsFile: true
        DeploymentSettingsFile: $(settingJSON)
        AsyncOperation: true
        MaxAsyncWaitTime: '60'
        ActivatePlugins: false
        PublishCustomizationChanges: true
  - ${{ if eq(parameters.environment, 'test') }}:
    - task: PowerPlatformImportSolution@2
      condition: eq(variables['settingJSON'], 'false')
      displayName: Import managed solution to ${{ parameters.environment }} instance
      inputs:
        authenticationType: 'PowerPlatformSPN'
        PowerPlatformSPN: 'PowerPlatform - Test instance'
        SolutionInputFile: '$(Build.ArtifactStagingDirectory)/$(SolutionName)/$(SolutionName)_managed.zip'
        AsyncOperation: true
        MaxAsyncWaitTime: '60'
        ActivatePlugins: false
        PublishCustomizationChanges: true
    - task: PowerPlatformImportSolution@2
      condition: endsWith(variables['settingJSON'], '.json')
      displayName: Import managed solution with settings to ${{ parameters.environment }} instance
      inputs:
        authenticationType: 'PowerPlatformSPN'
        PowerPlatformSPN: 'PowerPlatform - Test instance'
        SolutionInputFile: '$(Build.ArtifactStagingDirectory)/$(SolutionName)/$(SolutionName)_managed.zip'
        UseDeploymentSettingsFile: true
        DeploymentSettingsFile: $(settingJSON)
        AsyncOperation: true
        MaxAsyncWaitTime: '60'
        ActivatePlugins: false
        PublishCustomizationChanges: true
  - ${{ if eq(parameters.environment, 'uat') }}:
    - task: PowerPlatformImportSolution@2
      condition: eq(variables['settingJSON'], 'false')
      displayName: Import managed solution to ${{ parameters.environment }} instance
      inputs:
        authenticationType: 'PowerPlatformSPN'
        PowerPlatformSPN: 'PowerPlatform - UAT instance'
        SolutionInputFile: '$(Build.ArtifactStagingDirectory)/$(SolutionName)/$(SolutionName)_managed.zip'
        AsyncOperation: true
        MaxAsyncWaitTime: '60'
        ActivatePlugins: false
        PublishCustomizationChanges: true
    - task: PowerPlatformImportSolution@2
      condition: endsWith(variables['settingJSON'], '.json')
      displayName: Import managed solution with settings to ${{ parameters.environment }} instance
      inputs:
        authenticationType: 'PowerPlatformSPN'
        PowerPlatformSPN: 'PowerPlatform - UAT instance'
        SolutionInputFile: '$(Build.ArtifactStagingDirectory)/$(SolutionName)/$(SolutionName)_managed.zip'
        UseDeploymentSettingsFile: true
        DeploymentSettingsFile: $(settingJSON)
        AsyncOperation: true
        MaxAsyncWaitTime: '60'
        ActivatePlugins: false
        PublishCustomizationChanges: true
  - ${{ if eq(parameters.environment, 'production') }}:
    - task: PowerPlatformImportSolution@2
      condition: eq(variables['settingJSON'], 'false')
      displayName: Import managed solution to ${{ parameters.environment }} instance
      inputs:
        authenticationType: 'PowerPlatformSPN'
        PowerPlatformSPN: 'PowerPlatform - Prod instance'
        SolutionInputFile: '$(Build.ArtifactStagingDirectory)/$(SolutionName)/$(SolutionName)_managed.zip'
        AsyncOperation: true
        MaxAsyncWaitTime: '60'
        ActivatePlugins: false
        PublishCustomizationChanges: true
    - task: PowerPlatformImportSolution@2
      condition: endsWith(variables['settingJSON'], '.json')
      displayName: Import managed solution with settings to ${{ parameters.environment }} instance
      inputs:
        authenticationType: 'PowerPlatformSPN'
        PowerPlatformSPN: 'PowerPlatform - Prod instance'
        SolutionInputFile: '$(Build.ArtifactStagingDirectory)/$(SolutionName)/$(SolutionName)_managed.zip'
        UseDeploymentSettingsFile: true
        DeploymentSettingsFile: $(settingJSON)
        AsyncOperation: true
        MaxAsyncWaitTime: '60'
        ActivatePlugins: false
        PublishCustomizationChanges: true
